### ISSUE TITLE
cannot see cluster nodes in aws console

### ISSUE THREAD

**Issue by pete911** [pete911/eks-cluster#1]
If using different user to create cluster (e.g. restricted cli user), nodes cannot be displayed in aws console (even with root user):
<img width="1293" alt="Screen Shot 2020-12-13 at 15 03 07 pm" src="https://user-images.githubusercontent.com/567823/102015612-9322a300-3d54-11eb-90ff-446c49e0c8fd.png">

Add option to specify console users (or additional users) that will be added to `auth_config` configmap in `kube-system` namespace e.g for root. [iam identifiers](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html)
```
mapUsers: |
  - userarn: arn:aws:iam::<account_number>:root
    username: admin
    groups:
      - system:masters
```

If we cannot just append to config map but need to manage the whole configmap, we need to add this entry as well:
```
mapRoles: |
  - groups:
    - system:bootstrappers
    - system:nodes
    rolearn: arn:aws:iam::<account_number>:role/eks-main-eu-west-2-node
    username: system:node:{{EC2PrivateDNSName}}
```
